  <script language="javascript1.2"><!--
    var config = new Object();
    config.width = "100%";
    config.height = "200px";
    config.bodyStyle = 'background-color: white; font-family: "新細明體"; font-size: x-small;';
    config.debug = 0;
    
    config.fontnames = {
      "新細明體":        "新細明體",
      "標楷體":          "標楷體",
      "Arial":           "arial, helvetica, sans-serif",
      "Courier New":     "courier new, courier, mono",
      "Georgia":         "Georgia, Times New Roman, Times, Serif",
      "Tahoma":          "Tahoma, Arial, Helvetica, sans-serif",
      "Times New Roman": "times new roman, times, serif",
      "Verdana":         "Verdana, Arial, Helvetica, sans-serif",
      "impact":          "impact",
      "WingDings":       "WingDings"
    };
    config.fontsizes = {
      "1 (9 pt)":  "1",
      "2 (10 pt)": "2",
      "3 (12 pt)": "3",
      "4 (14 pt)": "4",
      "5 (18 pt)": "5",
      "6 (24 pt)": "6",
      "7 (36 pt)": "7"
    };
  
    config.fontstyles = [
      { name: "headline",     className: "headline",  classStyle: "font-family: arial black, arial; font-size: 28px; letter-spacing: -2px;" },
      { name: "arial red",    className: "headline2", classStyle: "font-family: arial black, arial; font-size: 12px; letter-spacing: -2px; color:red" },
      { name: "verdana blue", className: "headline4", classStyle: "font-family: verdana; font-size: 18px; letter-spacing: -2px; color:blue" }
    ];

    editor_generate('Content',config);
  // -->  
  </script>